spring:
  cloud:
    config:
      server:
        native:
          search-locations: C:/Users/yrz/Documents/GitHub/MyTest2/com.yang.test.java.spring.cloud/com.yang.test.java.spring.cloud.configserver/src/main/resources/conf/