package com.yang.test.java.jws.server;

import javax.xml.bind.annotation.XmlElement;

@SuppressWarnings("restriction")
public class Account {

	@XmlElement(namespace = "http://www.xikesoft.com/")
	private Integer AccountID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private Integer PlatAccountID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private Integer TenantCode;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Email;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String RealName;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String IDNumber;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private Integer LeftTime;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Phone;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private Integer AllowIDLogin;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String AccountNameLeftTime;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Status;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String CompanyTenantCode;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String ArchivingUser;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String ArchivingTime;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String ModifyUser;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String ModifyTime;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String CompanyDeptID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String LastLoginTime;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String IsVIP;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String VipRole;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String AccountCode;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Birth;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Gender;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Origin;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String StartTime;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Age;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String HasEditReport;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String Count;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String AssessCount;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String CompanyName;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String CompanyCode;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String HealthManageID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String PackageID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String ARID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String QRID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String SeqNumber;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String IsSeqNoBuildTeam;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private BasicInfo BasicInfo;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String PRID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String TIID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String rState;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String PlanPackageID;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String InterposeState;
	@XmlElement(namespace = "http://www.xikesoft.com/")
	private String IsChangeSex;
}