server:
  port: 6666
spring:
  boot:
    admin:
      client:
        url: http://192.168.10.19:8788
        instance:
          service-url: http://192.168.8.70:6666
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true
    reload:
      enabled: true
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"