spring:
  data:
    mongodb:
      one:
        uri: mongodb://192.168.10.237:27411/test
      two:
        uri: mongodb://192.168.10.237:27411/test
      three:
        uri: mongodb://192.168.10.237:27411/test