spring:
  data:
    mongodb:
      one:
        uri: mongodb://192.168.10.26:27017/test_tenantgroup
      two:
        uri: mongodb://192.168.10.26:27017/test_tenantgroup
      three:
        uri: mongodb://192.168.10.26:27017/test_tenantgroup