spring:
  data:
    mongodb:
      primary:
        uri: mongodb://192.168.10.228:27017/test_rhb_5
      one:
        uri: mongodb://192.168.10.228:27017/test_rhb_5
      two:
        uri: mongodb://192.168.10.229:27017/test_rhb_5
      three:
        uri: mongodb://192.168.10.225:27017/test_rhb_5