spring:
  data:
    mongodb:
      one:
        uri: mongodb://192.168.10.238:27017/recyclerecord
      two:
        uri: mongodb://192.168.10.238:27017/recyclerecord
      three:
        uri: mongodb://192.168.10.238:27017/recyclerecord