spring:
  data:
    mongodb:
      one:
        uri: mongodb://192.168.10.225:27017/test_source
      two:
        uri: mongodb://192.168.10.228:27017/test_source
      three:
        uri: mongodb://192.168.10.229:27017/test_source