spring:
  data:
    mongodb:
      one:
        uri: mongodb://192.168.10.19:27017/test
      two:
        uri: mongodb://192.168.10.19:27017/test
      three:
        uri: mongodb://192.168.10.19:27017/test