server:
  port: 9999
  tomcat:
    basedir: /media/monitor
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    user: 
      password: 90c3debd-0562-4de4-89fb-6a05c9f9ee2b
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info","shutdown"]