server:
  port: 9999
  tomcat:
    basedir: /media/monitor
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info","shutdown"]