spring:
  redis:
#    default:
#      host: 192.168.30.120
#      port: 6379
#      jedis:
#        pool: 
#          maxActive: 10
#          maxWait: -1
#          maxIdle: 5
#          minIdle: 0
#          timeout: 0
#    default: 
#      password: 123456
#      sentinel:
#        master: mymaster
#        nodes: 172.17.153.247:26379,172.17.153.254:26379,172.17.153.244:26379
    default:
      type: 2
      cluster:
        nodes: 192.168.10.228:27001,192.168.10.228:27002,192.168.10.228:27003,192.168.10.229:27004,192.168.10.229:27005,192.168.10.229:27006
      lettuce:
        pool:
          max-active: 1000
          max-idle: 10
          min-idle: 5
          max-wait: -1
    two:
      type: 0
      host: 192.168.30.120
      port: 6379
      jedis:
        pool: 
          maxActive: 10
          maxWait: -1
          maxIdle: 5
          minIdle: 0
          timeout: 0