spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:p6spy:mysql://192.168.10.10/yrz?useUnicode=true&characterEncoding=UTF-8
mybatis-plus:
  typeAliasesPackage: com.yang.test.java.springboot.entity
  mapperLocations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  configuration:
#    interceptors:
#      - com.yang.test.java.springboot.intercept.SqlStatementInterceptor