server:
  port: 12345
spring:
  datasource:
    username: root
    password: Lenovo@@7788
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.20:3306/lyzhhw4?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
mybatis:
  typeAliasesPackage: com.yang.test.java.springboot.entity
  mapperLocations: classpath:mapper/*.xml