server:
  port: 8762
management: 
  security:  
    enabled: false # spring-boot 1.5.2之后严格执行安全策略，所以需要配置这个为false  
info: #定义各种额外的详情给服务端显示  
  app:  
    name: "@project.name@" #从pom.xml中获取  
    description: "@project.description@"  
    version: "@project.version@"  
    spring-boot-version: "@project.parent.version@"
endpoints:
  sensitive: false
  shutdown:
    enabled: true