
package com.yang.test.java.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceTestService", targetNamespace = "http://webservice.java.test.yang.com/", wsdlLocation = "http://localhost:9001/WebService/Test/doTest?wsdl")
public class WebServiceTestService
    extends Service
{

    private final static URL WEBSERVICETESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICETESTSERVICE_EXCEPTION;
    private final static QName WEBSERVICETESTSERVICE_QNAME = new QName("http://webservice.java.test.yang.com/", "WebServiceTestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9001/WebService/Test/doTest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICETESTSERVICE_WSDL_LOCATION = url;
        WEBSERVICETESTSERVICE_EXCEPTION = e;
    }

    public WebServiceTestService() {
        super(__getWsdlLocation(), WEBSERVICETESTSERVICE_QNAME);
    }

    public WebServiceTestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICETESTSERVICE_QNAME, features);
    }

    public WebServiceTestService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICETESTSERVICE_QNAME);
    }

    public WebServiceTestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICETESTSERVICE_QNAME, features);
    }

    public WebServiceTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceTestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceTest
     */
    @WebEndpoint(name = "WebServiceTestPort")
    public WebServiceTest getWebServiceTestPort() {
        return super.getPort(new QName("http://webservice.java.test.yang.com/", "WebServiceTestPort"), WebServiceTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceTest
     */
    @WebEndpoint(name = "WebServiceTestPort")
    public WebServiceTest getWebServiceTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.java.test.yang.com/", "WebServiceTestPort"), WebServiceTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICETESTSERVICE_EXCEPTION!= null) {
            throw WEBSERVICETESTSERVICE_EXCEPTION;
        }
        return WEBSERVICETESTSERVICE_WSDL_LOCATION;
    }

}
