eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 1.1.1.1
words: you,me,he4r
spring:
  rabbitmq:
    host: 172.28.51.33
    port: 5672
    username: test
    password: test
    virtual-host: test