spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #type: com.alibaba.druid.pool.DruidDataSource #配套druid pom
    url: jdbc:mysql://192.168.10.10:3306/t?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  typeAliasesPackage: com.yang.test.java.springboot.entity
  mapperLocations: classpath:mapper/*.xml