jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
      default:
        type: redis.lettuce
        keyConvertor: fastjson
        uri:
          - redis://192.168.30.120:50010
          - redis://192.168.30.120:50020
          - redis://192.168.30.120:50030
          - redis://192.168.30.121:50040
          - redis://192.168.30.121:50050
          - redis://192.168.30.121:50060