jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
#      default:
#        type: redis
#        keyConvertor: fastjson
#        poolConfig:
#          minIdle: 5
#          maxIdle: 20
#          maxTotal: 50
#        host: 127.0.0.1
#        port: 6379
      default:
        type: redis.lettuce
        keyConvertor: fastjson
        uri:
          - redis://172.17.202.154:26379
          - redis://172.17.202.148:26379
          - redis://172.17.202.152:26379