jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
      default:
        type: redis.lettuce
        keyConvertor: fastjson
        uri:
          - redis://192.168.10.85:7001