jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
      default:
        type: redis.lettuce
        keyConvertor: fastjson
        uri:
          - redis://192.168.10.20:7001
          - redis://192.168.10.20:7002
          - redis://192.168.10.20:7003
          - redis://192.168.10.22:7004
          - redis://192.168.10.22:7005
          - redis://192.168.10.22:7006
#      default:
#        type: redis
#        keyConvertor: fastjson
#        poolConfig:
#          minIdle: 5
#          maxIdle: 20
#          maxTotal: 50
#        host: 127.0.0.1
#        port: 6379