
package www.xikesoft.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceTest", targetNamespace = "http://example.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceTest {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://example.org", className = "www.xikesoft.com.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://example.org", className = "www.xikesoft.com.GetValueResponse")
    @Action(input = "http://example.org/WebServiceTest/getValueRequest", output = "http://example.org/WebServiceTest/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
