server:
  port: 8890
spring: 
  rabbitmq:
    host: 172.28.51.33
    port: 5672
    username: test
    password: test
    virtual-host: test
  cloud:
    stream:
      bindings:
        output:
          destination: my-test-channel