eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.238:3100/eureka
  instance:
    ip-address: 192.168.10.238
spring:
  zipkin:
    baseUrl: http://192.168.10.230:9411
  mysql: 
    master: 
      username: server
      password: 345c0467b656
      url: jdbc:mysql://192.168.10.90:4306/lyzhhw4?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    slave: 
      username: readonlylyzh
      password: 123456
      url: jdbc:mysql://192.168.10.229:5306/lyzhhw4?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    dw: 
      username: server
      password: 345c0467b656
      url: jdbc:mysql://192.168.10.90:4306/lyzhhw4?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    dw2:
      username: server
      password: 345c0467b656
      url: jdbc:mysql://192.168.10.90:4306/lyzhhw4?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
  data:
    mongodb:
      uri: mongodb://192.168.10.239:27017/test
  timer:
    kindsbtenantOutputTypeHourTimer: 0 0/1 * * * ?  ##产生量按小时(设备)汇总 ：每半小时执行一次
    kindrytenantOutputTypeHourTimer: 0 0/1 * * * ?  ##产生量按小时(人员)汇总 ：每半小时执行一次
dingding:
  dingDingToken: https://oapi.dingtalk.com/robot/send?access_token=9574707fda4e8569b033f1e61ffb24c33536dc7ce2ed142e58e0c46b7d058d8f

