eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.238:3100/eureka
  instance:
    ip-address: 192.168.10.238
spring:
  data:
    mongodb:
      uri: mongodb://192.168.10.239:27017/test
