eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.238:3100/eureka
  instance:
    ip-address: 192.168.10.239
spring:
  zipkin:
    baseUrl: http://192.168.10.240:9411
  redis:
    cluster:
      nodes: 192.168.10.228:27001,192.168.10.228:27002,192.168.10.228:27003,192.168.10.229:27004,192.168.10.229:27005,192.168.10.229:27006
    standalone:
      host: 192.168.10.90
      port: 6379
      database: 0
  kafka:
    consumer:
      bootstrap-servers: 192.168.10.239:9092
    producer:
      bootstrap-servers: 192.168.10.239:9092
      properties:
        max.request.size: 104857600
  data:
    mongodb:
      primary:
        uri: mongodb://192.168.10.239:27017/test
      first:
        uri: mongodb://192.168.10.225:27017/test_source
        firstSourceList: 1,4,7,10
      second:
        uri: mongodb://192.168.10.228:27017/test_source
        secondSourceList: 2,5,8,11
      third:
        uri: mongodb://192.168.10.229:27017/test_source
        thirdSourceList: 3,6,9,12
      tenantgroup:
        uri: mongodb://192.168.10.228:27017/test_tenantgroup
      tenantscoreaccount:
        uri: mongodb://192.168.10.229:27017/test_tenantscoreaccount
canal:
  server: 192.168.30.121
data:
  logfile:
    path: /tmp/lyzh/logs/canal/canal
consumerOpend: 1
