
package www.xikesoft.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceTest", targetNamespace = "http://www.xikesoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceTest {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://www.xikesoft.com/", className = "www.xikesoft.com.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://www.xikesoft.com/", className = "www.xikesoft.com.InitResponse")
    @Action(input = "http://www.xikesoft.com/WebServiceTest/initRequest", output = "http://www.xikesoft.com/WebServiceTest/initResponse")
    public void init();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AccountInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AccountInfo", className = "www.xikesoft.com.AccountInfo")
    @ResponseWrapper(localName = "AccountInfoResponse", targetNamespace = "http://www.xikesoft.com/", className = "www.xikesoft.com.AccountInfoResponse")
    @Action(input = "http://www.xikesoft.com/WebServiceTest/AccountInfoRequest", output = "http://www.xikesoft.com/WebServiceTest/AccountInfoResponse")
    public String accountInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        WebServiceTestDto arg0);

}
